### ISSUE TITLE
#Refactoring : Unused files

### ISSUE THREAD

**Issue by d4n0n-myself** [itis-anete/InfoSystem#12]
Нужны ли нам эти страницы да и другие неиспользуемые объекты?

**Comment by d4n0n-myself** [comment]
![Снимок экрана 2019-03-09 в 13 08 04](https://user-images.githubusercontent.com/34159440/54070093-4cde0d00-426d-11e9-8725-e1d061908352.png)

**Comment by Helmoz** [comment]
Хз, pages вроде не нужны, а что еще неспользуемого там есть?
