### ISSUE TITLE
Front bug

### ISSUE THREAD

**Issue by d4n0n-myself** [itis-anete/InfoSystem#13]
![Снимок экрана 2019-03-09 в 13 20 53](https://user-images.githubusercontent.com/34159440/54070219-469c6080-426e-11e9-882a-b19ce57c3297.png)

**Comment by Helmoz** [comment]
Сообщай о переименовании контроллеров или их методов, там жесткий url до методов прописан, из-за того что EntityTypeController стал TypeController сломалось.

**Comment by Helmoz** [comment]
А ну и метод опять зачем-то удалил на получение всех типов.
