### ISSUE TITLE
Возвращать экземпляр сущности после добавления и изменения

### ISSUE THREAD

**Issue by Helmoz** [itis-anete/InfoSystem#15]
В EntityController/Add - вернуть сущность;
В TypeController/Add - вроде сделал, потестить;
В ValueController/EditValue - после update не подгружается attribute.
Вообще предложение из методов репозитория add и update возвращать не bool, а добавленный или измененный объект(тут хз)

**Comment by d4n0n-myself** [comment]
>Вообще предложение из методов репозитория add и update возвращать не bool, а добавленный или измененный объект(тут хз)

@Helmoz  зачем?

**Comment by Helmoz** [comment]
@d4n0n-myself Ну как ты сделал тоже нормально работает

**Comment by aneteanetes** [comment]
@d4n0n-myself что бы получить изменённую или сохранённую сущность, она может быть и другой. Одна из самых здравых идей

**Comment by aneteanetes** [comment]
Вот нахер out параметры сразу

**Comment by d4n0n-myself** [comment]
[commit](https://github.com/itis-anete/InfoSystem/commit/f42ed88c025d10ea2d264329de64fc8ad5b5a447)
