### ISSUE TITLE
Ошибка при добавлении атрибута сущности

### ISSUE THREAD

**Issue by Helmoz** [itis-anete/InfoSystem#20]
При добавлении сущности с одинаковыми keys после добавления возвращается не та сущность, которая была добавлена.

**Comment by Helmoz** [comment]
Подозреваю, что ошибка где-то тут 
![image](https://user-images.githubusercontent.com/22022397/54502114-060da880-493a-11e9-8a6e-376b8457368f.png)

**Comment by Helmoz** [comment]
Пример:
Существует атрибут { key: complex:product, value: 46}, добавляем атрибут {key: complex:product, value: 61}. В бд добавит нормально, но вернет первую сущность.

**Comment by d4n0n-myself** [comment]
Разве это вообще допустимая ситуация?

**Comment by d4n0n-myself** [comment]
Пока исправлю так, надо думать по поводу допустимости данной ситуации. @Helmoz

**Comment by Helmoz** [comment]
Ну да, ключи то могу быть одинаковыми, те же самые complex:product. @d4n0n-myself

**Comment by Helmoz** [comment]
Как вариант, можно попытаться найти сущность по всем 4 свойствам атрибута, это 100% будет нужная запись. @d4n0n-myself

**Comment by d4n0n-myself** [comment]
Окей
