### ISSUE TITLE
Составить список методов которые вызываются на фронте.

### ISSUE THREAD

**Issue by Helmoz** [itis-anete/InfoSystem#30]
Проверить все модули store и компоненты

**Comment by Halloneo** [comment]
UserController:

TypeController:
-Get
-Add

RoleController:
-Create

EntityController:
-GetByTypeName
-Add
-Delete

PropertyController:
-GetAttributeValue
-GetByTypeName
-Add
-Delete
-Update

**Comment by Helmoz** [comment]
@d4n0n-myself Собственно остальные я думаю можно удалить

**Comment by d4n0n-myself** [comment]
Нет необходимости
