### ISSUE TITLE
Добавить получение системных атрибутов при загрузке меню

### ISSUE THREAD

**Issue by d4n0n-myself** [itis-anete/InfoSystem#33]
api/Entity/GetByTypeName?typeName=menuitem - вызывается изначально
api/Property/GetByTypeName вызывается для каждого элемента menuitem

**Comment by Helmoz** [comment]
@d4n0n-myself Ага, из этого нужно сделать готовое меню, что бы 1 запросом в контроллер получить все menuitems.

**Comment by Helmoz** [comment]
@d4n0n-myself  хз как тебе удобнее отдавать. Можно анонимку в json сериализовать.
Типа: [ {titile: 'Home', link: '/', icon: 'home' }, {title: 'Registries', link: 'registries', icon: 'list'}, ... ]
