### ISSUE TITLE
Не получается использовать мутацию из другого модуля

### ISSUE THREAD

**Issue by Halloneo** [itis-anete/InfoSystem#9]
Не получается выполнить мутацию setLoading из модуля index.js в модуле entities.js

**Comment by Halloneo** [comment]
https://kodehauz.com/blog/access-state-another-module-nuxt
Возможно поможет

**Comment by Halloneo** [comment]
https://stackoverflow.com/questions/42606091/change-another-module-state-from-one-module-in-vuex

**Comment by Helmoz** [comment]
Ошибку исправил, делаем store в классическом моде, потом возможно переделаю
